import 'package:cached_network_image/cached_network_image.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
import 'package:intl/intl.dart';
import 'package:mechaku/models/models.dart';
import 'package:mechaku/providers/providers.dart';
import 'package:mechaku/theme.dart';
import 'package:mechaku/ui/pages/pages.dart';
import 'package:provider/provider.dart';
import 'package:shimmer_animation/shimmer_animation.dart';

part 'best_seller_item.dart';
part 'category_item.dart';
part 'new_arrival_item.dart';
part 'spinkit_loading.dart';
part 'basic_header.dart';
part 'wishlist_item.dart';
part 'product_tile.dart';
